version: "3.5"

services:
    frontend-node-alpine:
        build:
            context: .
            dockerfile: Dockerfile.frontend.node.alpine
        depends_on:
            - backend-node-alpine  
        ports:
            - 5000:5000
        container_name: frontend-node-alpine
    
    backend-node-alpine:
        build:
            context: .
            dockerfile: Dockerfile.backend.node.alpine
        ports:
            - 8000:8000
        container_name: backend-node-alpine
    