FROM node:12-alpine

EXPOSE 8000

ENV FRONT_URL=http://localhost:5000 

COPY ./backend-example-docker /home/node/app
WORKDIR /home/node/app
RUN npm install && chown -R node:node /home/node/app

USER node

CMD ["npm","start"]