version: '3.5'

services:
  frontend1.10:
    image: frontend1.10
    build:
      context: ~/github/devops_docker/Part1/Ex-1.10/
    ports:
      - 5000:5000
    container_name: frontend1.10

  backend1.11:
    image: backend1.11
    build:
      context: ~/github/devops_docker/Part1/Ex-1.11/
    volumes:
      - ./logs.txt:/usr/src/backend-example-docker/logs.txt
    ports:
      - 8000:8000
    container_name: backend1.11
    environment:
      - REDIS=redis
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
