FROM python:2.7.11-alpine

RUN addgroup -S webapp && \
    adduser -S webapp -G webapp && \
    mkdir /webapp && chown webapp:webapp /webapp
COPY ./webapp /webapp
WORKDIR /webapp
RUN pip install -r requirements.txt

USER webapp

EXPOSE 5000

CMD ["python","app.py"]
